import { create } from "zustand";

export const useAppStore = create((set) => ({
  user: JSON.parse(localStorage.getItem("user")) || null,
  users: null,
  stations: [],
  kolonkamarka: [],
  ltd: null,
  partners: [],
  payment: [],
  dailyreports: [],
  partnersDailyReports: [],
  addItemModal: false,
  sendingData: null,
  addItemModalOperators: false,
  regions: [],
  cities: [],
  licenses: [],
  ngsertificates: [],
  humidity: [],
  gasanalyzers: [],
  prodinsurance: [],
  lifeinsurance: [],
  ecology: [],
  ecologytwo: [],
  ik: [],
  pilot: [],
  shayba: [],
  water: [],
  electric: [],
  kolonka: [],
  manometr: [],
  termometr: [],
  voltmetr: [],
  shlang: [],
  ppk: [],
  educ: [],
  elprotec: [],
  mol: [],
  smazka: [],
  ger: [],
  aptek: [],
  hokim: [],
  contract: [],
  apz: [],
  gastx: [],
  elektrtx: [],
  suvtx: [],
  gasloyiha: [],
  elektrloyiha: [],
  suvloyiha: [],
  inshloyiha: [],
  inshexpertiza: [],
  prodexpertiza: [],
  iden: [],
  foyda: [],

  setUser: (user) => {
    set(() => {
      if (user) {
        localStorage.setItem("user", JSON.stringify(user));
      } else {
        localStorage.removeItem("user");
      }
      return { user };
    });
  },
  setUsers: (users) => set((state) => ({ users })),
  setStations: (stations) => set((state) => ({ stations })),
  setKolonkamarka: (kolonkamarka) => set((state) => ({ kolonkamarka })),
  setLtd: (ltd) => set((state) => ({ ltd })),
  setPartners: (partners) => set((state) => ({ partners })),
  setPayment: (payment) => set((state) => ({ payment })),
  setDailyreports: (dailyreports) => set((state) => ({ dailyreports })),
  setPartnersDailyReports: (reports) => set({ partnersDailyReports: reports }),
  setRegions: (regions) => set((state) => ({ regions })),
  setCities: (cities) => set((state) => ({ cities })),
  setLicenses: (licenses) => set((state) => ({ licenses })),
  setNgsertificates: (ngsertificates) => set((state) => ({ ngsertificates })),
  setHumidity: (humidity) => set((state) => ({ humidity })),
  setGasanalyzers: (gasanalyzers) => set((state) => ({ gasanalyzers })),
  setProdinsurance: (prodinsurance) => set((state) => ({ prodinsurance })),
  setLifeinsurance: (lifeinsurance) => set((state) => ({ lifeinsurance })),
  setEcology: (ecology) => set((state) => ({ ecology })),
  setEcologytwo: (ecologytwo) => set((state) => ({ ecologytwo })),
  setIk: (ik) => set((state) => ({ ik })),
  setPilot: (pilot) => set((state) => ({ pilot })),
  setShayba: (shayba) => set((state) => ({ shayba })),
  setWater: (water) => set((state) => ({ water })),
  setElectric: (electric) => set((state) => ({ electric })),
  setKolonka: (kolonka) => set((state) => ({ kolonka })),
  setManometr: (manometr) => set((state) => ({ manometr })),
  setTermometr: (termometr) => set((state) => ({ termometr })),
  setVoltmetr: (voltmetr) => set((state) => ({ voltmetr })),
  setShlang: (shlang) => set((state) => ({ shlang })),
  setPpk: (ppk) => set((state) => ({ ppk })),
  setEduc: (educ) => set((state) => ({ educ })),
  setElprotec: (elprotec) => set((state) => ({ elprotec })),
  setMol: (mol) => set((state) => ({ mol })),
  setSmazka: (smazka) => set((state) => ({ smazka })),
  setGer: (ger) => set((state) => ({ ger })),
  setAptek: (aptek) => set((state) => ({ aptek })),
  setHokim: (hokim) => set((state) => ({ hokim })),
  setContract: (contract) => set((state) => ({ contract })),
  setApz: (apz) => set((state) => ({ apz })),
  setGastx: (gastx) => set((state) => ({ gastx })),
  setElektrtx: (elektrtx) => set((state) => ({ elektrtx })),
  setSuvtx: (suvtx) => set((state) => ({ suvtx })),
  setGasloyiha: (gasloyiha) => set((state) => ({ gasloyiha })),
  setElektrloyiha: (elektrloyiha) => set((state) => ({ elektrloyiha })),
  setSuvloyiha: (suvloyiha) => set((state) => ({ suvloyiha })),
  setInshloyiha: (inshloyiha) => set((state) => ({ inshloyiha })),
  setInshexpertiza: (inshexpertiza) => set((state) => ({ inshexpertiza })),
  setProdexpertiza: (prodexpertiza) => set((state) => ({ prodexpertiza })),
  setIden: (iden) => set((state) => ({ iden })),
  setFoyda: (foyda) => set((state) => ({ foyda })),
  setAddItemModal: () =>
    set((state) => ({ addItemModal: !state.addItemModal })),
  setSendingData: (sendingData) => set({ sendingData }),
  setAddItemModalOperators: () =>
    set((state) => ({ addItemModalOperators: !state.addItemModalOperators })),
}));
